"""
Static data for Jal-Drishti Delhi.
Hotspots, drainage systems, historical records, ward definitions.
"""

HOTSPOTS = [
    {
        "id": 1,
        "name": "Minto Road",
        "lat": 28.6289,
        "lon": 77.2334,
        "elevation": 212,
        "base_risk": 0.85,
        "population": 50000,
        "area_sqkm": 2.3,
        "ward": "Central-01",
        "drainage_density": 0.72,
        "imperviousness": 0.88,
        "historical_incidents": 32,
    },
    {
        "id": 2,
        "name": "Kashmere Gate",
        "lat": 28.6692,
        "lon": 77.2289,
        "elevation": 215,
        "base_risk": 0.78,
        "population": 35000,
        "area_sqkm": 1.8,
        "ward": "North-03",
        "drainage_density": 0.65,
        "imperviousness": 0.82,
        "historical_incidents": 25,
    },
    {
        "id": 3,
        "name": "Kirari",
        "lat": 28.7747,
        "lon": 77.0371,
        "elevation": 208,
        "base_risk": 0.92,
        "population": 75000,
        "area_sqkm": 4.1,
        "ward": "Northwest-07",
        "drainage_density": 0.45,
        "imperviousness": 0.75,
        "historical_incidents": 38,
    },
    {
        "id": 4,
        "name": "ITO",
        "lat": 28.6289,
        "lon": 77.2497,
        "elevation": 211,
        "base_risk": 0.88,
        "population": 45000,
        "area_sqkm": 2.0,
        "ward": "Central-04",
        "drainage_density": 0.68,
        "imperviousness": 0.90,
        "historical_incidents": 35,
    },
    {
        "id": 5,
        "name": "Najafgarh",
        "lat": 28.6092,
        "lon": 76.9798,
        "elevation": 205,
        "base_risk": 0.95,
        "population": 90000,
        "area_sqkm": 5.2,
        "ward": "Southwest-12",
        "drainage_density": 0.38,
        "imperviousness": 0.65,
        "historical_incidents": 45,
    },
    {
        "id": 6,
        "name": "Yamuna Bank",
        "lat": 28.6414,
        "lon": 77.2833,
        "elevation": 209,
        "base_risk": 0.82,
        "population": 40000,
        "area_sqkm": 1.5,
        "ward": "East-02",
        "drainage_density": 0.55,
        "imperviousness": 0.70,
        "historical_incidents": 25,
    },
    {
        "id": 7,
        "name": "Safdarjung Enclave",
        "lat": 28.5562,
        "lon": 77.1901,
        "elevation": 216,
        "base_risk": 0.71,
        "population": 30000,
        "area_sqkm": 1.2,
        "ward": "South-06",
        "drainage_density": 0.80,
        "imperviousness": 0.85,
        "historical_incidents": 18,
    },
    {
        "id": 8,
        "name": "Pul Prahladpur",
        "lat": 28.4877,
        "lon": 77.2892,
        "elevation": 207,
        "base_risk": 0.89,
        "population": 55000,
        "area_sqkm": 2.8,
        "ward": "South-09",
        "drainage_density": 0.50,
        "imperviousness": 0.78,
        "historical_incidents": 28,
    },
    {
        "id": 9,
        "name": "Gandhi Nagar",
        "lat": 28.6631,
        "lon": 77.2464,
        "elevation": 213,
        "base_risk": 0.76,
        "population": 38000,
        "area_sqkm": 1.6,
        "ward": "East-05",
        "drainage_density": 0.62,
        "imperviousness": 0.80,
        "historical_incidents": 22,
    },
    {
        "id": 10,
        "name": "Tilak Nagar",
        "lat": 28.6414,
        "lon": 77.0955,
        "elevation": 210,
        "base_risk": 0.84,
        "population": 42000,
        "area_sqkm": 2.1,
        "ward": "West-08",
        "drainage_density": 0.58,
        "imperviousness": 0.82,
        "historical_incidents": 30,
    },
]


DRAINAGE_SYSTEMS = [
    {
        "id": 1,
        "name": "Najafgarh Drain",
        "length_km": 51,
        "status": "Silted",
        "ai_confidence": 87.3,
        "capacity_pct": 68,
        "flow_rate": 245,
        "last_cleaned": "2 months ago",
        "catchment_area": 350,
    },
    {
        "id": 2,
        "name": "Barapullah Drain",
        "length_km": 28,
        "status": "Clear",
        "ai_confidence": 94.1,
        "capacity_pct": 92,
        "flow_rate": 180,
        "last_cleaned": "1 week ago",
        "catchment_area": 120,
    },
    {
        "id": 3,
        "name": "Gazipur Drain",
        "length_km": 22,
        "status": "Blocked",
        "ai_confidence": 91.8,
        "capacity_pct": 34,
        "flow_rate": 85,
        "last_cleaned": "4 months ago",
        "catchment_area": 95,
    },
    {
        "id": 4,
        "name": "Shahdara Drain",
        "length_km": 18,
        "status": "Clear",
        "ai_confidence": 89.5,
        "capacity_pct": 88,
        "flow_rate": 160,
        "last_cleaned": "2 weeks ago",
        "catchment_area": 80,
    },
    {
        "id": 5,
        "name": "Supplementary Drain",
        "length_km": 14,
        "status": "Silted",
        "ai_confidence": 76.2,
        "capacity_pct": 61,
        "flow_rate": 120,
        "last_cleaned": "3 months ago",
        "catchment_area": 65,
    },
    {
        "id": 6,
        "name": "Mori Gate Drain",
        "length_km": 12,
        "status": "Clear",
        "ai_confidence": 92.7,
        "capacity_pct": 85,
        "flow_rate": 95,
        "last_cleaned": "10 days ago",
        "catchment_area": 55,
    },
]


HISTORICAL_YEARLY = {
    "years": list(range(2016, 2027)),
    "incidents": [25, 30, 28, 32, 40, 35, 38, 42, 35, 28, 14],
    "damage_crores": [30, 40, 35, 45, 60, 50, 55, 65, 48, 38, 18],
    "people_affected": [180000, 220000, 200000, 250000, 310000, 270000, 290000, 330000, 260000, 210000, 100000],
}

HISTORICAL_MONTHLY_AVG = {
    "months": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "avg_incidents": [3, 4, 3, 2, 6, 18, 32, 38, 25, 12, 4, 2],
    "avg_rainfall_mm": [20, 30, 25, 15, 40, 120, 180, 200, 150, 80, 30, 15],
}

AFFECTED_AREAS = [
    {"area": "Najafgarh", "incidents": 45, "avg_depth_m": 1.8, "people_affected": 450000},
    {"area": "Kirari", "incidents": 38, "avg_depth_m": 1.6, "people_affected": 380000},
    {"area": "ITO", "incidents": 35, "avg_depth_m": 1.5, "people_affected": 350000},
    {"area": "Minto Road", "incidents": 32, "avg_depth_m": 1.7, "people_affected": 320000},
    {"area": "Pul Prahladpur", "incidents": 28, "avg_depth_m": 1.4, "people_affected": 280000},
    {"area": "Yamuna Bank", "incidents": 25, "avg_depth_m": 1.3, "people_affected": 250000},
    {"area": "Tilak Nagar", "incidents": 30, "avg_depth_m": 1.2, "people_affected": 200000},
    {"area": "Gandhi Nagar", "incidents": 22, "avg_depth_m": 1.1, "people_affected": 180000},
    {"area": "Safdarjung", "incidents": 18, "avg_depth_m": 0.9, "people_affected": 150000},
    {"area": "Kashmere Gate", "incidents": 25, "avg_depth_m": 1.3, "people_affected": 220000},
]

EMERGENCY_CONTACTS = [
    {"agency": "MCD Control Room", "number": "1800-111-6772", "type": "Toll Free"},
    {"agency": "Delhi Police", "number": "100 / 112", "type": "Emergency"},
    {"agency": "NDRF", "number": "9711-077-372", "type": "Direct"},
    {"agency": "Fire Department", "number": "101", "type": "Emergency"},
    {"agency": "Flood Control Room", "number": "011-2327-1945", "type": "Direct"},
    {"agency": "PWD Helpline", "number": "1800-111-0135", "type": "Toll Free"},
]

# Ward-level readiness parameters for Pre-Monsoon Readiness Score
WARD_ZONES = [
    {"zone": "North Delhi", "wards": 42, "base_drainage_score": 72, "pump_infra": 68, "terrain_score": 65, "historical_prep": 70},
    {"zone": "South Delhi", "wards": 44, "base_drainage_score": 78, "pump_infra": 75, "terrain_score": 80, "historical_prep": 76},
    {"zone": "East Delhi", "wards": 38, "base_drainage_score": 60, "pump_infra": 55, "terrain_score": 58, "historical_prep": 62},
    {"zone": "West Delhi", "wards": 40, "base_drainage_score": 65, "pump_infra": 62, "terrain_score": 70, "historical_prep": 67},
    {"zone": "Central Delhi", "wards": 32, "base_drainage_score": 70, "pump_infra": 72, "terrain_score": 60, "historical_prep": 68},
    {"zone": "New Delhi", "wards": 18, "base_drainage_score": 82, "pump_infra": 85, "terrain_score": 78, "historical_prep": 80},
    {"zone": "Northwest Delhi", "wards": 30, "base_drainage_score": 48, "pump_infra": 45, "terrain_score": 52, "historical_prep": 50},
    {"zone": "Southwest Delhi", "wards": 28, "base_drainage_score": 55, "pump_infra": 50, "terrain_score": 48, "historical_prep": 52},
]


# Planning / allocation configuration
RESOURCE_INVENTORY = {
    "pumps": 18,
    "field_teams": 7,
    "traffic_units": 4,
    "sms_batches": 3,
    "medical_units": 2,
    "evacuation_vehicles": 6,
}

ALLOCATION_WEIGHTS = {
    "flood_risk": 0.40,
    "population_exposure": 0.25,
    "readiness_gap": 0.20,
    "drainage_penalty": 0.10,
    "operational_urgency": 0.05,
}

PLANNING_RULES = {
    "critical_risk_threshold": 0.75,
    "high_risk_threshold": 0.50,
    "minimum_action_score": 35.0,
    "top_recommendation_limit": 6,
}


# Scenario presets for flood simulation
SCENARIO_PRESETS = [
    {
        "key": "normal_monsoon",
        "name": "Normal Monsoon",
        "description": "Seasonal rain with manageable drainage stress and moderate operational pressure.",
        "rainfall_mm": 35,
        "drainage_stress": 0.10,
        "readiness_penalty": 0.06,
        "resource_pressure": 0.12,
        "focus": "Monitoring and light intervention",
    },
    {
        "key": "heavy_rainfall",
        "name": "Heavy Rainfall",
        "description": "Sustained rain event with noticeable drainage stress and higher field response demand.",
        "rainfall_mm": 70,
        "drainage_stress": 0.22,
        "readiness_penalty": 0.12,
        "resource_pressure": 0.26,
        "focus": "Pump staging and traffic control",
    },
    {
        "key": "cloudburst",
        "name": "Cloudburst",
        "description": "Short-duration extreme rainfall with severe operational strain across low-lying zones.",
        "rainfall_mm": 110,
        "drainage_stress": 0.38,
        "readiness_penalty": 0.20,
        "resource_pressure": 0.45,
        "focus": "Rapid response and evacuation readiness",
    },
    {
        "key": "extreme_flood_event",
        "name": "Extreme Flood Event",
        "description": "Citywide extreme flood condition with maximum drainage stress and emergency posture.",
        "rainfall_mm": 150,
        "drainage_stress": 0.55,
        "readiness_penalty": 0.30,
        "resource_pressure": 0.65,
        "focus": "Emergency escalation and mass alerts",
    },
]
